# Generated by Django 2.0.4 on 2018-04-19 03:54

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='联系电话')),
                ('content', models.TextField(default='', max_length=255, verbose_name='内容详情')),
            ],
            options={
                'verbose_name': '意见反馈',
                'verbose_name_plural': '意见反馈',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('version', models.CharField(default='1.0.0', max_length=10, verbose_name='版本号')),
                ('depends', models.CharField(blank=True, max_length=10, null=True, verbose_name='依赖版本')),
                ('install', models.URLField(null=True, verbose_name='下载链接')),
                ('sha1sum', models.CharField(blank=True, max_length=64, null=True, verbose_name='校验码')),
                ('channel', models.CharField(choices=[('1000', '官网'), ('1001', '91助手'), ('1002', '百度'), ('1003', '安卓'), ('1004', '豌豆荚'), ('1005', '应用宝'), ('1006', '360'), ('1007', '应用汇'), ('1008', '魅族'), ('1009', 'N多网'), ('1010', 'PP助手'), ('1011', '淘宝'), ('1012', '机锋网'), ('1013', '金立'), ('1014', '小米'), ('1015', '华为'), ('1016', '搜狗'), ('1017', '安智'), ('1018', '沃商店'), ('1019', 'itools'), ('1020', '电信爱游戏'), ('1021', '优亿市场'), ('1022', '应用贝'), ('1023', 'googleplay'), ('1024', '安粉网')], max_length=10, verbose_name='渠道')),
                ('summary', models.TextField(default='', verbose_name='日志')),
                ('platform', models.CharField(choices=[('ios', 'IOS'), ('android', 'Android')], default='android', max_length=50, verbose_name='APP平台')),
                ('constraint', models.BooleanField(default=False, verbose_name='强更')),
            ],
            options={
                'verbose_name': 'APP 版本升级',
                'verbose_name_plural': 'APP 版本升级',
            },
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('version', 'channel')},
        ),
    ]
