# Generated by Django 2.0.4 on 2018-04-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_feedback_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='storage',
            field=models.FileField(default='', max_length=255, upload_to='', verbose_name='内容详情'),
        ),
    ]
