# Generated by Django 2.0.4 on 2018-04-19 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('subject', models.CharField(default='', max_length=255, verbose_name='消息主题')),
                ('content', models.TextField(default='', verbose_name='消息正文')),
                ('extra', jsonfield.fields.JSONField(default={'data': '', 'type': ''}, verbose_name='附加内容')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='推送给用户')),
            ],
            options={
                'verbose_name': '消息中心',
                'verbose_name_plural': '消息中心',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='姓名')),
                ('nick', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('', '未知'), ('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('credit', models.IntegerField(default='50', verbose_name='用户积分')),
                ('avatar', imagekit.models.fields.ProcessedImageField(default='avatar/default.jpg', null=True, upload_to='avatar', verbose_name='头像')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='数字币余额')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
